//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negistics_Project.EntityframeWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Disconts
    {
        public long Id { get; set; }
        public int ProductID { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateFinish { get; set; }
        public double Volume { get; set; }
        public int MinQuantity { get; set; }
        public string Description { get; set; }
    }
}
